# Generated by Django 3.2.7 on 2021-09-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
