# Generated by Django 3.2.7 on 2021-11-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Фото'),
        ),
    ]
