# Generated by Django 3.2.7 on 2021-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211114_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Аватарка'),
        ),
    ]
